[package]
name = "socketpunch"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
dashmap = "6.2.1"
fastwebsockets = { version = "0.10.0", features = ["upgrade"] }
flume = "0.12.0"
http = "1.4.0"
http-body-util = "0.1.3"
hyper = "1.9.0"
hyper-util = "0.1.20"
rand = "0.10.1"
rustls = "0.23.40"
tokio = { version = "1.52.3", features = ["full"] }
tokio-rustls = "0.26.4"
url = "2.5.8"
webpki-roots = "1.0.7"
